const property = {
	_id: 's101',
	name: 'Ribeira Charming Duplex',
	type: 'House',
	imgUrls: ['https://e26e9b.jpg', 'otherImg.jpg'],
	price: 80.0,
	summary: 'Fantastic duplex apartment...',
	capacity: 8,
	amenities: ['TV', 'Wifi', 'Kitchen', 'Smoking allowed', 'Pets allowed', 'Cooking basics'],
	accessibility: ['Free parking on premises', 'Elevator', 'Pool', 'Hot tub'],
	bathrooms: 2,
	bedrooms: 3,
	beds: 4,
	rules: ['No parties or events', 'No smoking', 'No pets'],
	labels: ['Top of the world', 'Trending', 'Play', 'Tropical'],
	host: {
		_id: 'u101',
		fullname: 'Davit Pok',
		imgUrl: 'https://a0.muscache.com/im/pictures/fab79f25-2e10-4f0f-9711-663cb69dc7d8.jpg?aki_policy=profile_small',
	},
	loc: {
		country: 'Portugal',
		countryCode: 'PT',
		city: 'Lisbon',
		address: '17 Kombo st',
		lat: -8.61308,
		lng: 41.1413,
	},
	reviews: [
		{
			id: 'madeId',
			txt: 'Very helpful hosts. Cooked traditional...',
			rate: 4,
			by: {
				_id: 'u102',
				fullname: 'user2',
				imgUrl: '/img/img2.jpg',
			},
		},
	],
}